version: "3.8"

services:
  deadfellaz-automated-deadhunterz:
    image: bananaztech/deadfellaz-automated-deadhunterz:latest
    container_name: deadfellaz-automated-deadhunterz-prod
    restart: always
    environment:
      DB_PORT: 3306
      DB_HOST: "example.com"
      DB_USER: "Key-API"
      DB_PWD: "example"
      DB_NAME: "keys"

networks:
  default:
    external:
      name: bots